name: Build Android APK
on:
  push:
    branches: [ main ]

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Code auschecken
        uses: actions/checkout@v4

      - name: Web to APK Builder ausführen
        uses: cemcoe/web-to-apk-action@v1
        with:
          entryPoint: 'index.html'
          app_name: 'prête'
          app_id: 'com.mathilde.prete'
