name: Build Android APK
on:
  push:
    branches: [ main ]

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Code auschecken
        uses: actions/checkout@v4

      - name: Web to APK Builder ausführen
        uses: cemcoe/web-to-apk-action@v1
        with:
          web-dir: '.'
          app-name: 'prête'
          app-id: 'com.mathilde.prete'

      - name: APK zum Download bereitstellen
        uses: actions/upload-artifact@v4
        with:
          name: prete-android-app
          path: '*.apk'
